"""empty message

Revision ID: 154913086ea3
Revises: 8500f07c49db
Create Date: 2023-01-25 14:05:55.130694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154913086ea3'
down_revision = '8500f07c49db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_atk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_def', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('base_def')
        batch_op.drop_column('base_atk')
        batch_op.drop_column('base_hp')
        batch_op.drop_column('base_xp')

    # ### end Alembic commands ###
