"""empty message

Revision ID: 3aa2df343d82
Revises: 3f5528715612
Create Date: 2023-01-23 15:54:28.308736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa2df343d82'
down_revision = '3f5528715612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('pokemon_img_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('pokemon_img_key', ['img'])
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
