"""empty message

Revision ID: 3f5528715612
Revises: e6bca9c1176c
Create Date: 2023-01-22 11:41:51.862229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5528715612'
down_revision = 'e6bca9c1176c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['img'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
