"""empty message

Revision ID: 8500f07c49db
Revises: 0a25acccf11c
Create Date: 2023-01-25 12:36:41.902854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8500f07c49db'
down_revision = '0a25acccf11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_id_fkey')
    )
    # ### end Alembic commands ###
